title: M. Andrea Salazar Perea
logo: assets/logo.png
description: Bienvenid@ a mi portafolio de proyectos de Análisis de Datos.
Medio de contacto:
- 📧 **e-mail:** ma.salazarperea@gmail.com
Sígueme a través de:
- 🔗 **LinkedIn:** linkedin.com/in/andrea-salazar-data
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
